### PR TITLE
Add azuredeploy-minimal.json and button

### PR DESCRIPTION
**Pull request by hosungsmsft**
Not 100% sure if this is a good idea, but here it goes anyway, for your comments.

### CODE REVIEW

**Comment by rgardler** [comment]
Applicable to #47 (document minimal deployment)

**Comment by rgardler** [comment]
I'm uncomfortable with this approach. It makes things cluttered in the project root. I believe that folks will deploy the minimum and then complain it is not performant. Then again, if we don't provide adequate guidance people will deploy the maximal and complain it is too expensive for their needs.

We have to think about who we are targeting here. We are after the scale users. Those that need to optimize and fine tune their deployments to manage high loads. 

I would much rather we had good documentation via tooltips in the main template to guide people via the portal deploying. These tooltips should link back to full documentation here.

That said, I do think having examples like this that the documentation can refer to is sensible. I can imagine a range of these (e.g. minimal, small school, medium school, highly scalable). But these can be provided via parameter files rather than new templates. This would allow users to move between "sizes" by redeploying using new parameters.

Why did you choose to do it with a template that wraps our main template? was it only so you could provide the deploy button?

**Comment by hosungsmsft** [comment]
I knew your response would be along this line... :)

I totally agree with you on supporting various sizes through the parameters files, but I don't think it's realistic to expect everyone to deploy this template through CLI. I originally wanted to add a new parameters file for this config and add a button that'll work with that parameters file, but I couldn't find how to associate a parameters file with a button href link, so I had to do it this way. If you know how to achieve this, please let me know. If it's not supported, maybe we should ask ARM team to add that capability to the "Deploy to Azure" button link?

Again, this assumes that parameters files can be used only with CLI, and that most people won't try our templates on CLI initially, so I think it's valuable to provide a button, and I couldn't find a way to pass a parameters file to the button with the original/main template.

**Comment by rgardler** [comment]
I'm not sure why you are focusing on CLI vs Portal. In the portal users are given the option of providing values for all parameters. So, as long as they are well documented and have sensible defaults, then they are catered for.

**Comment by hosungsmsft** [comment]
Discussion taking place offline, agreed we better not take this approach, so closing this PR without merging.

**Pull request closed without merging**
