### PR TITLE
add elasticsearch creation as an option

### PR DESCRIPTION
**Pull request by CatalystAUInf**

### CODE REVIEW

**Comment by CatalystAUInf** [comment]
pull request for issue #29

**Comment by rgardler** [comment]
Thanks for this change. LGTM.

This work duplicates some recent (unmerged) work on the templates in #32 in which @hosungsmsft has been updating the conditional execution to use the logic expressions in ARM (which didn't exist when the original templates were written).

I'm merging this and @hosungsmsft will update his PR to accommodate these changes.

**Comment by CatalystAUInf** [comment]
Hi @rgardler - the commit b358c71 was the latest commit for this pull request. Please make sure this commit is merged too.

Thanks.

**Comment by rgardler** [comment]
It was merged: `2 parents f029f04 + b358c71 commit [f7fa6ebf7aa82f98959435f82a42015f58c30b04](https://github.com/Azure/Moodle/commit/f7fa6ebf7aa82f98959435f82a42015f58c30b04)` which includes `nested/{elastic.json → elastic1.json} `

However, #32 which was an merged immediately afterwards replaced most of this with a different implementation which removed the need for the `elastic0` and `elastic1` files. Hence the current master brings the file back again in its original name.

**Comment by hosungsmsft** [comment]
Hello @CatalystAUInf - Thanks for your contribution again, and sorry to overwrite your PR almost immediately. @rgardler made me make O365 plugins optional in #32, and I made the elastic search optional as well, with ARM "command" that removes all the *config[01].json hack. It was concurrently/independently done by both of us, so hopefully you understand this quick overwrite. Thanks again for your contribution!

**Comment by CatalystAUInf** [comment]
Hi @hosungsmsft and @rgardler - yes, it is all making sense now. Thank you for the update.

**Pull request merged**
