### PR TITLE
HTTP to HTTPS Redirect

### LINKED ISSUE #102: Add HTTP -> HTTPS redirection on App Gateway config
#98 added the Azure App Gateway support (fixing #31), but it lacks the http://siteurl -> https://siteurl redirection, which should be very easy with an Azure App Gateway example ([doc](https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-http-redirect-cli)). Community contribution would be great on things like this.

### PR DESCRIPTION
**Pull request by ChrisLopezUK**
Fixes #102

### CODE REVIEW

**Comment by rgardler** [comment]
Hi @ChrisLopezUK Thank you so much for these contributions. we'll review ASAP.

@UmakanthOS FYI

**Comment by ChrisLopezUK** [comment]
Hi @UmakanthOS,

Have you got any feedback for me? I've got some other work in the pipeline that I would eventually like to get into this project.

**Comment by UmakanthOS** [comment]
Apologies for the delay Chris. Dropped off my plate. This looks good to go. Thanks for your contributions!

**Comment by rgardler** [comment]
Sorry closed in error. I'm merging now @UmakanthOS has reviewed.

**Comment by rgardler** [comment]
Thank you very much for your contribution.

**Pull request merged**
